### ISSUE TITLE
大佬我拉下来您的项目后，一直报错这个

### ISSUE THREAD

**Issue by zhoujianli1016** [yechaoa/wanandroid_jetpack#1]
Value '/Library/Java/JavaVirtualMachines/jdk-11.jdk/Contents/Home' given for org.gradle.java.home Gradle property is invalid (Java home supplied is invalid)

**Comment by yechaoa** [comment]
gradle.properties文件中把java路径改成你自己的，或者直接删掉，自己修改配置。
